ALTER TABLE tv_channels ADD COLUMN IF NOT EXISTS backup_urls JSONB DEFAULT '[]';
ALTER TABLE tv_channels ADD COLUMN IF NOT EXISTS on_demand BOOLEAN NOT NULL DEFAULT false;
ALTER TABLE tv_channels ADD COLUMN IF NOT EXISTS on_demand_timeout INTEGER NOT NULL DEFAULT 30;
ALTER TABLE tv_channels ADD COLUMN IF NOT EXISTS on_demand_server_id INTEGER REFERENCES servers(id) ON DELETE SET NULL;
